### PR TITLE
Improved output formatting, with option for CSV/JSON

### PR DESCRIPTION
**Pull request by archy-bold**
This PR improves the output formatting to allow users to choose for `-Format csv` or `-Format json` for improved output handling.

Default "csv" mode will output valid CSV rather than the old comma-separated format that could cause issues when dates, tweets, or user display names contained commas.

The "json" option outputs a list of JSON strings for each tweet in the format `{id, url, text, username, fullname, timestamp}`.

The IDE also did some code linting to imports and remove spacing, which I've opted to leave in.

This could be further improved by moving the `FormatTweets` function out of the `Scrape` function, but I left it working as it used to.

### CODE REVIEW

**Comment by archy-bold** [comment]
Examples:

```bash
$ ./twint-lite -Query "(from:WD_CFC) since:2023-01-31_17:30:00_UTC  until:2023-01-31_21:45:00_UTC" -Instance birdsite.xanny.family -Format json
{"id":1620537242551992320,"url":"https://twitter.com/WD_CFC/status/1620537242551992320","text":"FT: Wythenshawe Town 0-3 West. A sensational second-half display and a big three points heading back up the Airport line!  ⚽ Matthews  Davis  Kirongozi","username":"@WD_CFC","fullname":"West Didsbury \u0026 Chorlton","timestamp":"Jan 31, 2023 · 9:39 PM UTC"}
{"id":1620536293645225984,"url":"https://twitter.com/WD_CFC/status/1620536293645225984","text":"90+1. Another West sub as we enter an unknown amount of added time  as Delaney replaces Swift.","username":"@WD_CFC","fullname":"West Didsbury \u0026 Chorlton","timestamp":"Jan 31, 2023 · 9:35 PM UTC"}
{"id":1620535833609764865,"url":"https://twitter.com/WD_CFC/status/1620535833609764865","text":"89. West sub. Eme off and replaced by Westall.","username":"@WD_CFC","fullname":"West Didsbury \u0026 Chorlton","timestamp":"Jan 31, 2023 · 9:33 PM UTC"}
{"id":1620532753333907456,"url":"https://twitter.com/WD_CFC/status/1620532753333907456","text":"77. Penalty to Wythy. You know what happened next. Still 3-0 to West. 🧤","username":"@WD_CFC","fullname":"West Didsbury \u0026 Chorlton","timestamp":"Jan 31, 2023 · 9:21 PM UTC"}
```

```bash
$ ./twint-lite -Query "(from:WD_CFC) since:2023-01-31_17:30:00_UTC  until:2023-01-31_21:45:00_UTC" -Instance birdsite.xanny.family -Format csv
1620537242551992320,https://twitter.com/WD_CFC/status/1620537242551992320,"Jan 31, 2023 · 9:39 PM UTC",@WD_CFC,West Didsbury & Chorlton,FT: Wythenshawe Town 0-3 West. A sensational second-half display and a big three points heading back up the Airport line!  ⚽ Matthews  Davis  Kirongozi
1620536293645225984,https://twitter.com/WD_CFC/status/1620536293645225984,"Jan 31, 2023 · 9:35 PM UTC",@WD_CFC,West Didsbury & Chorlton,90+1. Another West sub as we enter an unknown amount of added time  as Delaney replaces Swift.
1620535833609764865,https://twitter.com/WD_CFC/status/1620535833609764865,"Jan 31, 2023 · 9:33 PM UTC",@WD_CFC,West Didsbury & Chorlton,89. West sub. Eme off and replaced by Westall.
1620532753333907456,https://twitter.com/WD_CFC/status/1620532753333907456,"Jan 31, 2023 · 9:21 PM UTC",@WD_CFC,West Didsbury & Chorlton,77. Penalty to Wythy. You know what happened next. Still 3-0 to West. 🧤
```

**Comment by archy-bold** [comment]
Further bug fixes:

1. Not stripping commas, semicolons, newlines, etc from tweet text as formatters handle them now
2. Tweet IDs are strings, since they can cause floating point number issues
3. Exiting if no tweets are found

**Comment by twisted-nematic57** [comment]
[This got famous over on r/ProgrammerHumor](https://www.reddit.com/r/ProgrammerHumor/comments/11o3z51/comment/jbqpsai/?utm_source=share&utm_medium=web2x&context=3)

**Comment by wise-introvert** [comment]
> [This got famous over on r/ProgrammerHumor](https://www.reddit.com/r/ProgrammerHumor/comments/11o3z51/comment/jbqpsai/?utm_source=share&utm_medium=web2x&context=3)

Hello fellow traveller!

**Comment by aarush-salgania** [comment]
> [This got famous over on r/ProgrammerHumor](https://www.reddit.com/r/ProgrammerHumor/comments/11o3z51/comment/jbqpsai/?utm_source=share&utm_medium=web2x&context=3)

hola yall

**Comment by afkvido** [comment]
> [This got famous over on r/ProgrammerHumor](https://www.reddit.com/r/ProgrammerHumor/comments/11o3z51/comment/jbqpsai/?utm_source=share&utm_medium=web2x&context=3)

hell yeah it did

**Review by JrSchild — APPROVED** [review]

**Comment by xybrs** [comment]
LGTM. Greetings from programmer humor

**Comment by PROxZIMA** [comment]
$42,000 for a single API? Hell nahh

**Comment by pielco11** [comment]
Hello everyone,

sorry for missing this.

Nice work btw

image

**Pull request merged**
